# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LHPPWallet' do
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Network
  pod 'Alamofire', '~> 4.7.3'
  pod 'SwiftyJSON', '~> 4.2.0'
  pod 'ReachabilitySwift', '~> 4.3.0'

  # Utils
  pod 'CryptoSwift', '~> 0.12.0'
  pod 'DeviceKit', '~> 1.9.0'
  pod 'PhoneNumberKit', '~> 2.5.0'
  pod 'NVActivityIndicatorView', '~> 4.4.0'
  pod 'Swinject', '~> 2.5'
  pod 'SwinjectStoryboard', '~> 2.1.0'

  # Rules
  pod 'SwiftLint', '~> 0.27.0'

  # UI Design
  pod 'Material', '~> 2.16.4'
  pod 'SideMenu', '~> 5.0.1'
  pod 'MXSegmentedPager', '~> 3.3.0'

  # Google
  pod 'GoogleMaps', '~> 2.7.0'
  
  pod 'GooglePlaces', '~> 2.7.0'

  target 'LHPPWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LHPPWalletUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
